/**
 * PROPOSAL URL SIGNING
 *
 * Signs proposal URLs with HMAC to prevent unauthorized access.
 * URL format: /vinforslag/{id}?s={signature}
 *
 * Without a valid signature the page returns 404 —
 * only links generated by us (admin) will work.
 */

import { createHmac, timingSafeEqual } from 'crypto';

function getSecret(): string {
  const secret = process.env.PROPOSAL_SIGNING_SECRET || process.env.SUPABASE_SERVICE_ROLE_KEY || '';
  if (!secret) throw new Error('Missing PROPOSAL_SIGNING_SECRET');
  return secret;
}

/**
 * Generate HMAC signature for a proposal ID.
 * Returns a 16-char hex string (64 bits — sufficient for URL signing).
 */
export function signProposalId(proposalId: string): string {
  return createHmac('sha256', getSecret())
    .update(`proposal:${proposalId}`)
    .digest('hex')
    .substring(0, 16);
}

/**
 * Verify that the signature matches the proposal ID.
 * Uses timing-safe comparison.
 */
export function verifyProposalSignature(proposalId: string, signature: string): boolean {
  if (!signature || signature.length !== 16) return false;

  const expected = signProposalId(proposalId);

  try {
    return timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expected)
    );
  } catch {
    return false;
  }
}

/**
 * Build a full proposal URL with signature.
 * Usage: buildProposalUrl('uuid-here') → '/vinforslag/uuid-here?s=abc123...'
 */
export function buildProposalUrl(proposalId: string): string {
  const sig = signProposalId(proposalId);
  return `/vinforslag/${proposalId}?s=${sig}`;
}
