/**
 * PUBLIC WINE PROPOSAL PAGE - Server Component
 *
 * Shows wines matched for a specific restaurant — no login required.
 * Used in outreach emails to lower the threshold for engagement.
 *
 * SECURITY: Requires valid HMAC signature in ?s= query param.
 * Without it → 404. Only links generated by admin will work.
 *
 * NEVER exposes prices, MOQ, stock, notes, or SKU.
 */

import { notFound } from 'next/navigation';
import { Metadata } from 'next';
import { getSupabaseAdmin } from '@/lib/supabase-server';
import { verifyProposalSignature } from '@/lib/proposal-token';
import ProposalView from '@/components/proposal/ProposalView';

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

type PageProps = {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ s?: string }>;
};

export interface ProposalWine {
  id: string;
  name: string;
  producer: string;
  vintage: number | string | null;
  region: string | null;
  country: string | null;
  grape: string | null;
  color: string | null;
  description: string | null;
  appellation: string | null;
  alcohol_pct: number | null;
  bottle_size_ml: number | null;
  organic: boolean | null;
  biodynamic: boolean | null;
  reason: string | null;
  supplier_name: string;
  supplier_type: string;
}

export interface ProposalData {
  id: string;
  restaurant_name: string;
  restaurant_city: string | null;
  message: string | null;
  wines: ProposalWine[];
}

async function getProposal(id: string): Promise<ProposalData | null> {
  if (!UUID_REGEX.test(id)) return null;

  const adminClient = getSupabaseAdmin();

  // Fetch proposal
  const { data: proposal, error: proposalError } = await adminClient
    .from('wine_proposals')
    .select('id, restaurant_name, restaurant_city, message, expires_at')
    .eq('id', id)
    .single();

  if (proposalError || !proposal) return null;

  // Check expiry
  if (proposal.expires_at && new Date(proposal.expires_at) < new Date()) {
    return null;
  }

  // Fetch items with wine + supplier data (explicit safe columns)
  const { data: items } = await adminClient
    .from('wine_proposal_items')
    .select(`
      reason,
      sort_order,
      supplier_wine_id,
      supplier_wines (
        id, name, producer, vintage, region, country, grape, color,
        description, appellation, alcohol_pct, bottle_size_ml,
        organic, biodynamic,
        suppliers ( namn, type )
      )
    `)
    .eq('proposal_id', id)
    .order('sort_order', { ascending: true });

  if (!items || items.length === 0) return null;

  const wines: ProposalWine[] = items
    .filter((item: any) => item.supplier_wines)
    .map((item: any) => {
      const w = item.supplier_wines;
      const s = w.suppliers;
      return {
        id: w.id,
        name: w.name,
        producer: w.producer,
        vintage: w.vintage,
        region: w.region,
        country: w.country,
        grape: w.grape,
        color: w.color,
        description: w.description,
        appellation: w.appellation,
        alcohol_pct: w.alcohol_pct,
        bottle_size_ml: w.bottle_size_ml,
        organic: w.organic,
        biodynamic: w.biodynamic,
        reason: item.reason,
        supplier_name: s?.namn || 'Okänd leverantör',
        supplier_type: s?.type || '',
      };
    });

  return {
    id: proposal.id,
    restaurant_name: proposal.restaurant_name,
    restaurant_city: proposal.restaurant_city,
    message: proposal.message,
    wines,
  };
}

export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const { s } = await searchParams;

  // Don't leak metadata for unsigned URLs
  if (!s || !verifyProposalSignature(id, s)) {
    return { title: 'Vinförslag' };
  }

  const data = await getProposal(id);
  if (!data) return { title: 'Vinförslag' };

  const supplierCount = new Set(data.wines.map((w) => w.supplier_name)).size;

  return {
    title: `Vinförslag till ${data.restaurant_name}`,
    description: `${data.wines.length} utvalda viner från ${supplierCount} leverantör${supplierCount !== 1 ? 'er' : ''}`,
    robots: { index: false, follow: false },
  };
}

export default async function ProposalPage({ params, searchParams }: PageProps) {
  const { id } = await params;
  const { s } = await searchParams;

  // Verify HMAC signature — no valid signature = 404
  if (!s || !verifyProposalSignature(id, s)) {
    notFound();
  }

  const data = await getProposal(id);

  if (!data) {
    notFound();
  }

  return <ProposalView proposal={data} sig={s} />;
}
